---
title: "Team proj 1"
author: "Team 6 purple"
date: "9/17/2020"
output: html_document
---

### ---Environment setup, delete this caption for final report---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
knitr::opts_chunk$set(out.width = '50%')
knitr::opts_chunk$set(fig.align="center")
```

```{r library,message=FALSE}
library(tidyverse) # Data wrangling
library(ggplot2) # Plotting

# For logistic regression
library(arm)
library(car)
library(pROC)
library(e1071)
library(caret)
```

### ---Data wrangling
```{r import data}
# CHANGE DIRECTORY
# income <- read.table("C:/Users/renha/Desktop/IDS702/lalondedata.txt",header = TRUE,sep = ",",stringsAsFactors = FALSE,row.names = 'X')
income = read.table(file = "D:/MIDS/fall 2020/702 modeling/dataset/lalondedata.txt",
                    header = T, sep = ",", dec = ".")
```

```{r}
# Change the variable to factor levels
income = income %>% mutate(
        inc78 = case_when(
                re78 == 0 ~ 0,
                re78 > 0 ~ 1, )
        )

income$inc78_factor <- as.factor(income$inc78)
income$treat <- as.factor(income$treat)
income$black <- as.factor(income$black)
income$hispan <- as.factor(income$hispan)
income$married <- as.factor(income$married)
income$nodegree <- as.factor(income$nodegree)
```


### ---EDA

#### Response variable vs categorical variables

```{r}
apply(table(income[,c("inc78_factor","treat")])/sum(table(income[,c("inc78_factor","treat")])),
      2,function(x) x/sum(x))
apply(table(income[,c("inc78_factor","black")])/sum(table(income[,c("inc78_factor","black")])),
      2,function(x) x/sum(x))
apply(table(income[,c("inc78_factor","hispan")])/sum(table(income[,c("inc78_factor","hispan")])),
      2,function(x) x/sum(x))
apply(table(income[,c("inc78_factor","married")])/sum(table(income[,c("inc78_factor","married")])),
      2,function(x) x/sum(x))
apply(table(income[,c("inc78_factor","nodegree")])/sum(table(income[,c("inc78_factor","nodegree")])),
      2,function(x) x/sum(x))
apply(table(income[,c("inc78_factor","educ")])/sum(table(income[,c("inc78_factor","educ")])),
      2,function(x) x/sum(x))
```

#### Response variable vs categorical variables

```{r}
# Examine the relations between response variable and educ,interaction??
ggplot(income, aes(x = educ, y = re78, colour = treat)) +
  labs(x = "Educ", y = "Income in 1978") +
  theme(legend.position="none") +
  geom_text(data = income,aes(label = treat), hjust = 0.5, vjust = 1)
```

```{r, echo=FALSE}
# Check interactions between age and other predictors: why age??
ggplot(data= income, aes(x=age, y=inc78_factor)) + geom_boxplot() + facet_wrap(~treat)
ggplot(data= income, aes(x=age, y=inc78_factor)) + geom_boxplot() + facet_wrap(~black)
ggplot(data= income, aes(x=age, y=inc78_factor)) + geom_boxplot() + facet_wrap(~hispan)
ggplot(data= income, aes(x=age, y=inc78_factor)) + geom_boxplot() + facet_wrap(~married)
ggplot(data= income, aes(x=age, y=inc78_factor)) + geom_boxplot() + facet_wrap(~nodegree) # possible nodegree:age
```


#### Chi-square test for independence
```{r}
chisq.test(table(income[,c("nodegree","age")]))
chisq.test(table(income[,c("treat","educ")]))
chisq.test(table(income[,c("black","educ")]))
chisq.test(table(income[,c("married","educ")]))
chisq.test(table(income[,c("hispan","inc78_factor")])) # independent hispan inc78_factor
chisq.test(table(income[,c("black","inc78_factor")]))
chisq.test(table(income[,c("married","inc78_factor")])) # independent
chisq.test(table(income[,c("nodegree","inc78_factor")])) # independent

chisq.test(table(income[,c("hispan","age")])) # independent hispan age
chisq.test(table(income[,c("hispan","educ")]))
chisq.test(table(income[,c("hispan","black")]))
chisq.test(table(income[,c("hispan","nodegree")]))
chisq.test(table(income[,c("hispan","married")])) # independent hispan married
```