---
title: "Team proj 1"
author: "Team 6 purple"
date: "9/17/2020"
output: html_document
---

### ---Environment setup, delete this caption for final report---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
knitr::opts_chunk$set(out.width = '50%')
knitr::opts_chunk$set(fig.align="center")
```

```{r library,message=FALSE}
library(tidyverse) # Data wrangling
library(ggplot2) # Plotting

# For logistic regression
library(arm)
library(car)
library(pROC)
library(e1071)
library(caret)
```

### ---Data wrangling
```{r import data}
# CHANGE DIRECTORY
income <- read.table("C:/Users/renha/Desktop/IDS702/lalondedata.txt",header = TRUE,sep = ",",stringsAsFactors = FALSE,row.names = 'X')
#income = read.table(file = "D:/MIDS/fall 2020/702 modeling/dataset/lalondedata.txt", header = T, sep = ",", dec = ".")
```

```{r}
# Change the variable to factor levels
income = income %>% mutate(
        inc78 = case_when(
                re78 == 0 ~ 0,
                re78 > 0 ~ 1, )
        )

income$inc78_factor <- as.factor(income$inc78)
income$treat <- as.factor(income$treat)
income$black <- as.factor(income$black)
income$hispan <- as.factor(income$hispan)
income$married <- as.factor(income$married)
income$nodegree <- as.factor(income$nodegree)
mean(income$inc78)
```

### ---EDA

#### Response variable vs categorical variables

```{r}
apply(table(income[,c("inc78_factor","treat")])/sum(table(income[,c("inc78_factor","treat")])),
      2,function(x) x/sum(x))
apply(table(income[,c("inc78_factor","black")])/sum(table(income[,c("inc78_factor","black")])),
      2,function(x) x/sum(x)) # significant
apply(table(income[,c("inc78_factor","hispan")])/sum(table(income[,c("inc78_factor","hispan")])),
      2,function(x) x/sum(x))
apply(table(income[,c("inc78_factor","married")])/sum(table(income[,c("inc78_factor","married")])),
      2,function(x) x/sum(x))
apply(table(income[,c("inc78_factor","nodegree")])/sum(table(income[,c("inc78_factor","nodegree")])),
      2,function(x) x/sum(x))
apply(table(income[,c("inc78_factor","educ")])/sum(table(income[,c("inc78_factor","educ")])),
      2,function(x) x/sum(x))
```

#### Response variable vs categorical variables

```{r, echo=FALSE}
# Check interactions between age and other predictors: why age??
ggplot(data= income, aes(x=age, y=inc78_factor)) + geom_boxplot() + facet_wrap(~treat)
ggplot(data= income, aes(x=age, y=inc78_factor)) + geom_boxplot() + facet_wrap(~black)
ggplot(data= income, aes(x=age, y=inc78_factor)) + geom_boxplot() + facet_wrap(~hispan)
ggplot(data= income, aes(x=age, y=inc78_factor)) + geom_boxplot() + facet_wrap(~married)
ggplot(data= income, aes(x=age, y=inc78_factor)) + geom_boxplot() + facet_wrap(~nodegree) # possible nodegree:age
```


#### Chi-square test for independence
```{r}
chisq.test(table(income[,c("nodegree","age")])) 
chisq.test(table(income[,c("treat","educ")])) 
chisq.test(table(income[,c("black","educ")])) 
chisq.test(table(income[,c("married","educ")])) 
chisq.test(table(income[,c("hispan","inc78_factor")])) # independent hispan inc78_factor
chisq.test(table(income[,c("black","inc78_factor")]))
chisq.test(table(income[,c("married","inc78_factor")])) # independent
chisq.test(table(income[,c("nodegree","inc78_factor")])) # independent

chisq.test(table(income[,c("hispan","age")])) # independent hispan age
chisq.test(table(income[,c("hispan","educ")]))
chisq.test(table(income[,c("hispan","black")]))
chisq.test(table(income[,c("hispan","nodegree")]))
chisq.test(table(income[,c("hispan","married")])) # independent hispan married
```


### Model
```{r}
full <- glm(inc78_factor~treat+age+educ+black+hispan+married+nodegree+nodegree:age+treat:black+treat:hispan,family = binomial,data = income)
summary(full)
residFull <- residuals(full,"resp")
binnedplot(x=fitted(full),y=residFull,xlab="Pred. probabilities",col.int="red4",ylab="Avg. residuals",main="Binned residual plot",col.pts="navy") # 92% within SE band
```


```{r}
raw <- glm(inc78_factor~treat+age+educ+black+hispan+married+nodegree,family = binomial,data = income)
summary(raw)
```


```{r}
resid <- residuals(raw,"resp")
binnedplot(x=fitted(raw),y=resid,xlab="Pred. probabilities",col.int="red4",ylab="Avg. residuals",main="Binned residual plot",col.pts="navy") # 92% within SE band
```


```{r}
null <- glm(inc78_factor~treat,data=income,family=binomial)
selection <- step(null,scope=formula(full),direction="both",trace=0)
```

```{r}
fit1 <- glm(inc78_factor~treat+age+black,family = binomial,data = income)
anova(selection,fit1,test = 'Chisq')

fit2 <- glm(inc78_factor~age+treat*black,family = binomial,data = income)
anova(fit2,selection,test = 'Chisq')

fit3 <- glm(inc78_factor~age+black+treat*hispan,family = binomial,data = income)
anova(fit3,selection,test = 'Chisq')

fit4 <- glm(inc78_factor~black+treat*age,family = binomial,data = income)
anova(fit4,selection,test = 'Chisq') # treat:age significant

fit5 <- glm(inc78_factor~age+black+treat*educ,family = binomial,data = income)
anova(fit5,selection,test = 'Chisq')

fit6 <- glm(inc78_factor~age+black+treat*married,family = binomial,data = income)
anova(fit6,selection,test = 'Chisq')

fit7 <- glm(inc78_factor~age+black+treat*nodegree,family = binomial,data = income)
anova(fit7,selection,test = 'Chisq')

fit8 <- glm(inc78_factor~treat+black+age*nodegree,family = binomial,data = income)
anova(fit8,fit7,test = 'Chisq')

fit9 <- glm(inc78_factor~black+age*nodegree,family = binomial,data = income)
anova(fit9,selection,test = 'Chisq')
```

```{r}
final <- glm(inc78_factor~black+treat*age,family = binomial,data = income)
vif(final)
summary(final)
exp(final$coefficients)

residFinal <- residuals(final,"resp")
binnedplot(x=fitted(final),y=residFinal,xlab="Pred. probabilities",col.int="red4",ylab="Avg. residuals",main="Binned residual plot",col.pts="navy") # 92% within SE band
```
```{r}
anova(raw,final,test = 'Chisq')
Conf_mat <- confusionMatrix(as.factor(ifelse(fitted(final) >= 0.5, "1","0")),
                            as.factor(income$inc78_factor),positive = "1")
Conf_mat$table
Conf_mat$overall["Accuracy"];
Conf_mat$byClass[c("Sensitivity","Specificity")] #True positive rate and True negative rate

Conf_mat <- confusionMatrix(as.factor(ifelse(fitted(final) >= mean(income$inc78), "1","0")),
                            as.factor(income$inc78_factor),positive = "1")
Conf_mat$table
Conf_mat$overall["Accuracy"];
Conf_mat$byClass[c("Sensitivity","Specificity")] #True positive rate and True negative rate

roc(income$inc78_factor,fitted(final),plot=T,print.thres="best",print.auc=T,legacy.axes=T,col="red3")
roc(income$inc78_factor,fitted(raw),plot=T,legacy.axes=T,add=T,col="blue3")
legend('bottomright', c('final','raw'),lty=c(1,1),
       lwd=c(2,2),col=c('red3','blue3'))
```

## Part1

```{r}
income <- read.table("C:/Users/renha/Desktop/IDS702/lalondedata.txt",header = TRUE,sep = ",",stringsAsFactors = FALSE,row.names = 'X')
income$treat <- as.factor(income$treat)
income$black <- as.factor(income$black)
income$hispan <- as.factor(income$hispan)
income$married <- as.factor(income$married)
income$nodegree <- as.factor(income$nodegree)
income$change <- income$re78 - income$re74
summary(income)
```

```{r}
# continuous
hist(income$re78)
hist(log(income$re78))
pairs(income[,-c(1,4,5,6,7,11)])

plot(income$age,income$edu)
plot(income$age,income$re78)
plot(income$educ,income$re78)
```


```{r}
# categorical
ggplot(data= income, aes(x=treat, y=re78)) + geom_boxplot() 

ggplot(data= income, aes(x=as.factor(educ), y=re78)) + geom_boxplot() + facet_wrap(~treat)
ggplot(data= income, aes(x=black, y=re78)) + geom_boxplot() + facet_wrap(~treat) # significant individually
ggplot(data= income, aes(x=hispan, y=re78)) + geom_boxplot() + facet_wrap(~treat) # individually
ggplot(data= income, aes(x=married, y=re78)) + geom_boxplot() + facet_wrap(~treat) # individually
ggplot(data= income, aes(x=nodegree, y=re78)) + geom_boxplot() + facet_wrap(~treat) # individually

```

```{r}
ggplot(data= income, aes(x=treat, y=change)) + geom_boxplot() 

ggplot(data= income, aes(x=as.factor(educ), y=change)) + geom_boxplot() + facet_wrap(~treat)
ggplot(data= income, aes(x=black, y=change)) + geom_boxplot() + facet_wrap(~treat) # interaction
ggplot(data= income, aes(x=hispan, y=change)) + geom_boxplot() + facet_wrap(~treat) # individually
ggplot(data= income, aes(x=married, y=change)) + geom_boxplot() + facet_wrap(~treat) # interaction
#ggplot(data= income, aes(x=nodegree, y=change)) + geom_boxplot() + facet_wrap(~treat) 
ggplot(data= income, aes(x=treat, y=change)) + geom_boxplot() + facet_wrap(~nodegree) # individually
```


